apiVersion: v1
kind: ReplicationController
labels:
  app:my-app
spec:
  relicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort:80

        - name: tomcat-container
          image:  tomcat
          ports:
            - containerPort:8080
    selector:
      app:my-app 